# improvement: don't hard code env variables or the image in this way
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
    role: worker
    tier: backend
  name: rq-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
      role: worker
      tier: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        role: worker
        tier: backend
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: KEY
        - name: AWS_SECRET_ACCESS_KEY
          value: KEY
        image: ECR URI
        imagePullPolicy: Always
        command: ["python", "redis_worker.py"]
        name: rq-worker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}