apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
    tier: frontend
  name: web-flask
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: flask
    tier: frontend
  type: LoadBalancer
